# Generated by Django 2.1 on 2019-11-01 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('balance_change', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'balance_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(blank=True, max_length=32, null=True)),
                ('device', models.CharField(blank=True, max_length=32, null=True)),
                ('software_account', models.CharField(blank=True, max_length=32, null=True)),
                ('software_password', models.CharField(blank=True, max_length=32, null=True)),
                ('wechat_id', models.CharField(blank=True, max_length=32, null=True)),
                ('software_status', models.IntegerField(default=0, null=True)),
                ('wechat_status', models.IntegerField(default=0, null=True)),
                ('test_time', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks_information', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'device_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'website_auth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteBalanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=25, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('update_time', models.CharField(blank=True, max_length=20, null=True)),
                ('last_time_balance', models.FloatField(blank=True, null=True)),
                ('last_cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_balance_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=64, null=True)),
                ('device', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('ad_id', models.CharField(blank=True, max_length=300, null=True)),
                ('wechat_id', models.CharField(blank=True, max_length=20, null=True)),
                ('qq_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('online_number', models.CharField(blank=True, max_length=13, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('is_distributed', models.IntegerField(blank=True, null=True)),
                ('is_promoting', models.IntegerField(blank=True, null=True)),
                ('pid_list', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteDownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'website_download_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('record', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'website_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsitePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payee_account', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.CharField(blank=True, max_length=64, null=True)),
                ('payee_real_name', models.CharField(blank=True, max_length=64, null=True)),
                ('remark', models.CharField(blank=True, max_length=64, null=True)),
                ('order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('out_biz_no', models.CharField(blank=True, max_length=64, null=True)),
                ('pay_date', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('first_pay_status', models.IntegerField(blank=True, null=True)),
                ('success_time', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'website_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteUserinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=16, null=True)),
                ('birthday', models.CharField(max_length=64, null=True)),
                ('tel', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('introduction', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=32, null=True)),
                ('auth_type', models.CharField(default='默认', max_length=32)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'website_userinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteTranRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('zfb_number', models.CharField(blank=True, max_length=30, null=True)),
                ('device', models.CharField(blank=True, max_length=64, null=True)),
                ('pay_date', models.CharField(blank=True, max_length=64, null=True)),
                ('order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('remark', models.CharField(blank=True, max_length=64, null=True)),
                ('out_biz_no', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('operator', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'website_tran_record',
            },
        ),
    ]
