# Generated by Django 2.1 on 2018-11-12 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonetCountAmountCreateTime',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('day_time', models.CharField(max_length=10)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monet_count_amount_create_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoneyAmount',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('day_time', models.CharField(max_length=10)),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'money_amount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoneyCountAmountSettlement',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('day_time', models.CharField(max_length=10)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'money_count_amount_settlement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoneyEstEffectCreateTime',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('day_time', models.CharField(max_length=10)),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'money_est_effect_create_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoneyEstEffectSettlementTime',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('day_time', models.CharField(max_length=10)),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'money_est_effect_settlement_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoneySettlement',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('day_time', models.CharField(max_length=10)),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'money_settlement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('create_time', models.CharField(blank=True, max_length=32, null=True)),
                ('click_time', models.CharField(max_length=32)),
                ('goods_info', models.CharField(blank=True, max_length=128, null=True)),
                ('goods_id', models.CharField(max_length=32)),
                ('wangwang', models.CharField(blank=True, max_length=64, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=64, null=True)),
                ('goods_num', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('goods_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(blank=True, max_length=32, null=True)),
                ('order_type', models.CharField(blank=True, max_length=32, null=True)),
                ('income_ratio', models.CharField(blank=True, max_length=32, null=True)),
                ('division', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_effect', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('settlement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('settlement_time', models.CharField(blank=True, max_length=32, null=True)),
                ('com_ratio', models.CharField(blank=True, max_length=32, null=True)),
                ('com_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service', models.CharField(blank=True, max_length=32, null=True)),
                ('sub_ratio', models.CharField(blank=True, max_length=32, null=True)),
                ('sub_price', models.CharField(blank=True, max_length=32, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=32, null=True)),
                ('platform', models.CharField(blank=True, max_length=32, null=True)),
                ('third_server', models.CharField(blank=True, max_length=64, null=True)),
                ('order_num', models.CharField(max_length=32)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('source_id', models.CharField(max_length=32)),
                ('source_name', models.CharField(blank=True, max_length=32, null=True)),
                ('ad_id', models.CharField(max_length=32)),
                ('ad_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'oa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OaReflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('create_time', models.CharField(blank=True, max_length=32, null=True)),
                ('click_time', models.CharField(max_length=32)),
                ('goods_info', models.CharField(blank=True, max_length=128, null=True)),
                ('goods_id', models.CharField(max_length=32)),
                ('wangwang', models.CharField(blank=True, max_length=64, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=64, null=True)),
                ('goods_num', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('goods_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(blank=True, max_length=32, null=True)),
                ('order_type', models.CharField(blank=True, max_length=32, null=True)),
                ('income_ratio', models.CharField(blank=True, max_length=32, null=True)),
                ('division', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_effect', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('settlement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('settlement_time', models.CharField(blank=True, max_length=32, null=True)),
                ('com_ratio', models.CharField(blank=True, max_length=32, null=True)),
                ('com_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service', models.CharField(blank=True, max_length=32, null=True)),
                ('sub_ratio', models.CharField(blank=True, max_length=32, null=True)),
                ('sub_price', models.CharField(blank=True, max_length=32, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=32, null=True)),
                ('platform', models.CharField(blank=True, max_length=32, null=True)),
                ('third_server', models.CharField(blank=True, max_length=64, null=True)),
                ('order_num', models.CharField(max_length=32)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('source_id', models.CharField(max_length=32)),
                ('source_name', models.CharField(blank=True, max_length=32, null=True)),
                ('ad_id', models.CharField(max_length=32)),
                ('ad_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'oa_reflection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlineStatua',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('end_time', models.CharField(max_length=20)),
                ('statua', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'online_statua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SumGoods',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('day_time', models.CharField(max_length=10)),
                ('sum_goods', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sum_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'website_auth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteBalanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=25, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('update_time', models.CharField(blank=True, max_length=20, null=True)),
                ('last_time_balance', models.FloatField(blank=True, null=True)),
                ('last_cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_balance_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=64, unique=True)),
                ('device', models.CharField(blank=True, max_length=64, null=True)),
                ('wechat_id', models.CharField(blank=True, max_length=20, null=True)),
                ('qq_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('online_number', models.CharField(blank=True, max_length=13, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField()),
            ],
            options={
                'db_table': 'website_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='websiteDeviceSession',
            fields=[
                ('device_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('datetime', models.CharField(blank=True, max_length=30, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'device_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(unique=True)),
                ('groupname', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'website_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteInputdata',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.CharField(blank=True, max_length=64, null=True)),
                ('data', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'website_inputdata',
                'ordering': ['-username', '-time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('record', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'website_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsitePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payee_account', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.CharField(blank=True, max_length=64, null=True)),
                ('payee_real_name', models.CharField(blank=True, max_length=64, null=True)),
                ('remark', models.CharField(blank=True, max_length=64, null=True)),
                ('order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('out_biz_no', models.CharField(blank=True, max_length=64, null=True)),
                ('pay_date', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'website_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteStaffAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_staff_achievement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteUserinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=16, null=True)),
                ('birthday', models.CharField(max_length=64, null=True)),
                ('tel', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('introduction', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=32, null=True)),
                ('auth_type', models.CharField(default='默认', max_length=32)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'website_userinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteShareholderinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_storage', models.FloatField()),
                ('already_storage', models.FloatField()),
                ('SH_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.WebsiteUserinfo', to_field='uid')),
                ('own_devices', models.ManyToManyField(to='website.WebsiteDevice')),
            ],
            options={
                'db_table': 'website_shareholderinfo',
            },
        ),
    ]
