# Generated by Django 2.1 on 2020-01-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TuPian',
            new_name='Userinfo',
        ),
    ]
