# Generated by Django 2.1 on 2020-01-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200114_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envent',
            name='eventID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='envent',
            name='userID',
            field=models.IntegerField(default=None),
        ),
    ]
