# Generated by Django 2.1 on 2018-11-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_djangoadminlog_djangocontenttype_djangomigrations_djangosession_monetcountamountcreatetime_moneyamou'),
    ]

    operations = [
    ]
