# Generated by Django 2.1 on 2019-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181112_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyOrderRatio',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('day_time', models.CharField(max_length=10)),
                ('sum_goods', models.IntegerField(blank=True, null=True)),
                ('order_ratio', models.FloatField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'money_order_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutputFromCibuluo',
            fields=[
                ('device_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_time', models.CharField(max_length=20)),
                ('total_customer', models.IntegerField(blank=True, null=True)),
                ('device_customer', models.IntegerField(blank=True, null=True)),
                ('total_count', models.FloatField(blank=True, null=True)),
                ('output_from_cibuluo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'output_from_cibuluo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteAccountOutputRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.TextField(blank=True, null=True)),
                ('request_month', models.CharField(blank=True, max_length=255, null=True)),
                ('real_output', models.FloatField(blank=True, null=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('raw_output', models.FloatField(blank=True, default=0.0, null=True)),
                ('output_from_cibuluo', models.FloatField(blank=True, default=0.0, null=True)),
                ('cost_payment', models.FloatField(blank=True, default=0.0, null=True)),
                ('belong_to_whom', models.CharField(blank=True, max_length=10, null=True)),
                ('belong_to_whom_id', models.IntegerField(blank=True, default=0, null=True)),
                ('belong_to_whom_ratio', models.FloatField(blank=True, default=0.0, null=True)),
                ('real_output_from_cibuluo', models.FloatField(blank=True, default=0.0, null=True)),
                ('cost_reserve', models.FloatField(blank=True, default=0.0, null=True)),
                ('this_month_reserve', models.FloatField(blank=True, default=0.0, null=True)),
                ('last_month_reserve', models.FloatField(blank=True, default=0.0, null=True)),
                ('cost_rent_base_customer', models.FloatField(blank=True, default=0.0, null=True)),
                ('cost_man_power_base_customer', models.FloatField(blank=True, default=0.0, null=True)),
                ('cost_device_base_customer', models.FloatField(blank=True, default=0.0, null=True)),
                ('raw_device_profit_base_customer', models.FloatField(blank=True, default=0.0, null=True)),
                ('raw_profit_base_customer', models.FloatField(blank=True, default=0.0, null=True)),
                ('profit_base_customer', models.FloatField(blank=True, default=0.0, null=True)),
                ('remark', models.TextField(blank=True, default='', null=True)),
                ('is_updated', models.IntegerField(blank=True, default=0, null=True)),
                ('cost_rent_base_device', models.FloatField(blank=True, default=0.0, null=True)),
                ('cost_man_power_base_device', models.FloatField(blank=True, default=0.0, null=True)),
                ('cost_device_base_device', models.FloatField(blank=True, default=0.0, null=True)),
                ('raw_device_profit_base_device', models.FloatField(blank=True, default=0.0, null=True)),
                ('raw_profit_base_device', models.FloatField(blank=True, default=0.0, null=True)),
                ('profit_base_device', models.FloatField(blank=True, default=0.0, null=True)),
                ('avg_profit', models.FloatField(blank=True, default=0.0, null=True)),
                ('record_source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'website_account_output_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteAccountRealOutputRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.TextField(blank=True, null=True)),
                ('request_month', models.CharField(blank=True, max_length=255, null=True)),
                ('real_output', models.FloatField(blank=True, null=True)),
                ('record_source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'website_account_real_output_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteDeviceMonthProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=10)),
                ('belong_to_whom', models.CharField(blank=True, max_length=10, null=True)),
                ('belong_to_whom_id', models.IntegerField(blank=True, null=True)),
                ('belong_to_whom_ratio', models.FloatField(blank=True, null=True)),
                ('account_name', models.CharField(blank=True, max_length=30, null=True)),
                ('request_month', models.CharField(blank=True, max_length=15, null=True)),
                ('output', models.FloatField(blank=True, null=True)),
                ('output_from_cibuluo', models.FloatField(blank=True, null=True)),
                ('cost_payment', models.FloatField(blank=True, null=True)),
                ('real_output_from_cibuluo', models.FloatField(blank=True, null=True)),
                ('avg_device_customer', models.FloatField(blank=True, null=True)),
                ('avg_all_device_customer', models.FloatField(blank=True, null=True)),
                ('cost_rent_base_device', models.FloatField(blank=True, null=True)),
                ('cost_man_power_base_device', models.FloatField(blank=True, null=True)),
                ('cost_device_base_device', models.FloatField(blank=True, null=True)),
                ('raw_device_profit_base_device', models.FloatField(blank=True, null=True)),
                ('profit_base_device', models.FloatField(blank=True, null=True)),
                ('avg_profit', models.FloatField(blank=True, null=True)),
                ('this_month_reserve', models.FloatField(blank=True, null=True)),
                ('cost_reserve', models.FloatField(blank=True, null=True)),
                ('cost_rent_base_customer', models.FloatField(blank=True, null=True)),
                ('cost_man_power_base_customer', models.FloatField(blank=True, null=True)),
                ('cost_device_base_customer', models.FloatField(blank=True, null=True)),
                ('raw_device_profit_base_customer', models.FloatField(blank=True, null=True)),
                ('raw_profit_sum_base_customer', models.FloatField(blank=True, null=True)),
                ('profit_base_customer', models.FloatField(blank=True, null=True)),
                ('last_month_reserve', models.FloatField(blank=True, null=True)),
                ('raw_profit_base_device', models.FloatField(blank=True, default=0.0, null=True)),
                ('raw_profit_base_customer', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'db_table': 'website_device_month_profit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteDeviceReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('reserve', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_device_reserve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteDeviceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_state', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'website_device_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteDownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'website_download_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteMonthCost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_wages', models.FloatField(blank=True, null=True)),
                ('rent', models.FloatField(blank=True, null=True)),
                ('device_cost', models.FloatField(blank=True, null=True)),
                ('cost_all', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_month_cost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteMonthProfitRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_month_profit_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsitePartnerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('partner_single_profit1', models.FloatField(blank=True, null=True)),
                ('partner_single_profit2', models.FloatField(blank=True, null=True)),
                ('partner', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_ratio', models.FloatField(blank=True, null=True)),
                ('partner_own_device_num', models.IntegerField(blank=True, null=True)),
                ('partner_profit', models.FloatField(blank=True, null=True)),
                ('single_profit_avg', models.FloatField(blank=True, null=True)),
                ('partner_single_cost', models.FloatField(blank=True, null=True)),
                ('month_single_profit', models.FloatField(blank=True, null=True)),
                ('partner_customer_avg', models.FloatField(blank=True, null=True)),
                ('partner_single_cibuluo', models.FloatField(blank=True, null=True)),
                ('partner_single_profit', models.FloatField(blank=True, null=True)),
                ('single_device_output', models.FloatField(blank=True, null=True)),
                ('single_device_cost', models.FloatField(blank=True, null=True)),
                ('single_device_profit', models.FloatField(blank=True, null=True)),
                ('partner_device_profit', models.FloatField(blank=True, null=True)),
                ('single_device_output_avg', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_partner_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsitePaymentRecord',
            fields=[
                ('device', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_time', models.CharField(max_length=20)),
                ('payment_sum', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_payment_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteShAlreadyReserveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.CharField(blank=True, max_length=255, null=True)),
                ('real_reserve', models.FloatField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_sh_already_reserve_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteShReserveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('logic_reserve', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_sh_reserve_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteTranRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('zfb_number', models.CharField(blank=True, max_length=30, null=True)),
                ('device', models.CharField(blank=True, max_length=64, null=True)),
                ('tran_time', models.CharField(blank=True, max_length=30, null=True)),
                ('tran_number', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('operator', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'website_tran_record',
            },
        ),
        migrations.AlterModelOptions(
            name='oa',
            options={'managed': False, 'ordering': ['-create_time']},
        ),
        migrations.AlterModelOptions(
            name='websiteinputdata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='websiteshareholderinfo',
            options={'managed': False},
        ),
    ]
