# Generated by Django 2.1 on 2019-10-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181112_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('balance_change', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'balance_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(blank=True, max_length=32, null=True)),
                ('device', models.CharField(blank=True, max_length=32, null=True)),
                ('software_account', models.CharField(blank=True, max_length=32, null=True)),
                ('software_password', models.CharField(blank=True, max_length=32, null=True)),
                ('wechat_id', models.CharField(blank=True, max_length=32, null=True)),
                ('software_status', models.IntegerField(default=0, null=True)),
                ('wechat_status', models.IntegerField(default=0, null=True)),
                ('test_time', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks_information', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'device_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteDownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'website_download_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteTranRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('zfb_number', models.CharField(blank=True, max_length=30, null=True)),
                ('device', models.CharField(blank=True, max_length=64, null=True)),
                ('pay_date', models.CharField(blank=True, max_length=64, null=True)),
                ('order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('out_biz_no', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('operator', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'website_tran_record',
            },
        ),
        migrations.AlterModelOptions(
            name='websiteshareholderinfo',
            options={'managed': False},
        ),
    ]
