# Generated by Django 2.1 on 2020-01-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200114_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envent',
            name='eventID',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='envent',
            name='userID',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
