# Generated by Django 2.1 on 2020-01-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200114_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
