# Generated by Django 2.1 on 2019-10-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20191024_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(blank=True, max_length=32, null=True)),
                ('device', models.CharField(blank=True, max_length=32, null=True)),
                ('software_account', models.CharField(blank=True, max_length=32, null=True)),
                ('wechat_id', models.CharField(blank=True, max_length=32, null=True)),
                ('software_status', models.IntegerField(default=0, null=True)),
                ('wechat_status', models.IntegerField(default=0, null=True)),
                ('test_time', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks_information', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'device_information',
            },
        ),
        migrations.AlterModelOptions(
            name='websitetranrecord',
            options={'managed': False},
        ),
    ]
