# Generated by Django 2.1 on 2020-01-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200114_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_openid',
            name='create_time',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
