# Generated by Django 2.1 on 2020-01-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_user_openid_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_openid',
            name='city',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='user_openid',
            name='position',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
