# Generated by Django 2.1 on 2020-01-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200115_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_openid',
            name='headimgurl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user_openid',
            name='subscribe',
            field=models.IntegerField(default=1),
        ),
    ]
