# Generated by Django 2.1 on 2020-01-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200115_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_openid',
            old_name='create_time',
            new_name='subscribe_time',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
